DROP TABLE user01 CASCADE CONSTRAINT;
DROP TABLE post01 CASCADE CONSTRAINT;
DROP SEQUENCE post01_postno_seq;

CREATE TABLE user01 (
    userid VARCHAR(20) PRIMARY KEY,
    userpw VARCHAR(20) NOT NULL,
    usernickname VARCHAR(20) NOT NULL
);

CREATE TABLE post01 (
    postno NUMBER(10) PRIMARY KEY,
    postdate DATE NOT NULL,
    userid VARCHAR(20) NOT NULL,
    ptitle VARCHAR(30) NOT NULL,
    pcontent VARCHAR(100) NOT NULL,
    surl VARCHAR(100) NOT NULL,
    stitle VARCHAR(100) NOT NULL,
    sartist VARCHAR(100) NOT NULL,
    salbum VARCHAR(100) NOT NULL
);

CREATE SEQUENCE post01_postno_seq START WITH 0 MINVALUE 0;

ALTER SESSION SET NLS_DATE_FORMAT = 'RRRR/MM/DD HH24:MI:SS';

COMMIT;